### ISSUE TITLE
odbc is missing

### ISSUE THREAD

**Issue by M-Mommsen** [ProgerXP/php-5.6-xp#5]
"Fatal error: Call to undefined function odbc_connect() ..."

And there is no .dll extension available!

I guess a simple "--with-odbc" would probably do it

**Comment by ProgerXP** [comment]
This port doesn't include ODBC extension. Try taking one from the archive at this topic: https://www.apachelounge.com/viewtopic.php?t=6334

See last posts in #4 for more info.
