### ISSUE TITLE
wrong OpenSSL hardcoded path

### ISSUE THREAD

**Issue by ghost** [ProgerXP/php-5.6-xp#6]
In libeay32.dll there is a hardcoded path
OPENSSLDIR: "c:/usr/local/ssl"
I belive this is wrong. It should point to php's directory or maybe "ssl" subdir in php's directory.

Thank you for this great project!

**Comment by ProgerXP** [comment]
That's default config path which is often compiled into various modules. It coming from openssl itself, it wasn't added by this port so no need to change it specifically.
