### ISSUE TITLE
"Maximum execution time exceeded"

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/php-5.6-xp#7]
It seems there is some problem with time-related functions in this port. Suddenly PHP (running under Apache of XAMPP) starts failing with "maximum execution time exceeded" immediately on request startup (no matter how large max_execution_time ini setting is). This occurs randomly - sometimes almost every request is failing, at other times only every 10th request or so is failing.

I suspect this has something to do with GetTickCount64. How we can track down this bug? @cshnik

**Comment by cshnik** [comment]
Fixed.
